version: '3.7'

services:
  frontend:
    build: .
    command: sh -c "npm rebuild esbuild && yarn dev"
    ports:
      - '3011:8000'
    env_file: .env
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
